---
title: "FIFA 2018 Predictions"
output: html_notebook
---

### Introduction

Importing Datasets
```{r}
library(ggplot2)
library(dplyr)

matches <- read.csv("results.csv") #Match details of different teams
fifa_ranking <- read.csv("fifa_ranking.csv") #Yearwise fifa rankings of various teams
fifa2018 <- read.csv("World Cup 2018 Dataset.csv") #ranks & other details of teams participating in FIFA 2018
```

Data Cleaning & Preprocessing
```{r}
#Selecting important columns
fifa_ranking <- subset(fifa_ranking,select=c('rank', 'country_full', 'country_abrv', 'cur_year_avg_weighted', 'rank_date','two_year_ago_weighted', 'three_year_ago_weighted'))

#Calculating weighted points
fifa_ranking$weighted_points <- fifa_ranking$cur_year_avg_weighted + fifa_ranking$two_year_ago_weighted + fifa_ranking$three_year_ago_weighted

#Changing Dates format
fifa_ranking$rank_date <- as.Date.POSIXct(fifa_ranking$rank_date)
matches$date <- as.Date.POSIXct(matches$date)

#Renaming team names for consistency
matches$team1[junk$nm == "B"] <- "b"

matches <- as.data.frame(lapply(matches, function(x){replace('German DR', 'Germany')}))

```

Visualization: FIFA 2018 Tableau Dashboard
#https://public.tableau.com/profile/mohit5191#!/vizhome/FIFA2018ExploratotyAnalysis/Dashboard1

Feature Extraction
```{r}

```

